---
baseURL: "http://undying.github.io"
languageCode: "en-us"
title: "My Digital Chronicle"
theme: "PaperMod"

menu:
  main:
    - identifier: about
      name: About
      url: /about/

params:
  socialIcons:
    - name: github
      url: "https://github.com/undying"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/2020593/kron"

services:
  googleAnalytics:
    ID: G-6EM4NECWNX
